name: spy
on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  hc-lib-spy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Spy on new lib releases
        id: lib_spy
        run: |
          echo "LATEST_RELEASES=$(./spy.mjs)" >> $GITHUB_OUTPUT
    outputs:
      latest-releases: ${{ steps.lib_spy.outputs.LATEST_RELEASES }}

  notify-on-latest-releases:
    needs: hc-lib-spy
    if: ${{ needs.hc-lib-spy.outputs.latest-releases }}
    runs-on: ubuntu-latest
    env:
      RELEASES_OUTPUT: ${{ needs.hc-lib-spy.outputs.latest-releases }}
    steps:
    - name: Print Output
      run: |
        echo ${RELEASES_OUTPUT}
    - name: Notify via Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: mail.collinsmuriuki.xyz
        server_port: 465
        secure: true
        username: ${{secrets.SMTP_USERNAME}}
        password: ${{secrets.SMTP_PASSWORD}}
        subject: hc-lib-spy Found New Releases!
        to: logs@collinsmuriuki.xyz
        from: Hc-Lib-Spy <no-reply@collinsmuriuki.xyz>
        body: |
          hc-lib-spy just detected the following new releases:
          ---
          ${{needs.hc-lib-spy.outputs.latest-releases}}
          ---
          best regards.
        ignore_cert: true
        priority: high