name: spy
on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  hc-lib-spy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Spy on new lib releases
        id: lib_spy
        run: |
          echo "LATEST_RELEASES=$(./spy.mjs)" >> $GITHUB_OUTPUT
    outputs:
      latest-releases: ${{ steps.lib_spy.outputs.LATEST_RELEASES }}

  notify-on-latest-releases:
    needs: hc-lib-spy
    if: ${{ needs.hc-lib-spy.outputs.latest-releases }}
    runs-on: ubuntu-latest
    env:
      RELEASES_OUTPUT: ${{ needs.hc-lib-spy.outputs.latest-releases }}
    steps:
    - name: Print Output
      run: |
        echo ${RELEASES_OUTPUT}
    - name: Notify via Email
      uses: hilarion5/send-mail@v1
      env:
        RELEASES_OUTPUT: ${{ needs.hc-lib-spy.outputs.latest-releases }}
      with:
        smtp-server: mail.collinsmuriuki.xyz
        smtp-port: 465
        smtp-secure: true
        from-email: no-reply@collinsmuriuki.xyz
        to-email: logs@collinsmuriuki.xyz
        username: secrets.SMTP_USERNAME
        password: secrets.SMTP_PASSWORD
        subject: hc-lib-spy New Releases!
        body: |
           hc-lib-spy just detected the following new releases:
           ${RELEASES_OUTPUT}
        html: |
          <p>hc-lib-spy just detected the following new releases:</p>
          <p>${RELEASES_OUTPUT}</p>